FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 go build -o /out/forge-server ./cmd/server

FROM alpine:3
RUN adduser -D forge
USER forge
COPY --from=build /out/forge-server /usr/local/bin/forge-server
EXPOSE 8080
ENTRYPOINT ["forge-server"]
